collections:
- bucket-list
- destinations
- travel-tips


collections:
  bucket-list:
    output: true
  destinations:
    output: true
  travel-tips:
    output: true


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /:title

jekyll-archives:
  enabled:
    - year
    permalinks:
      year: '/:year'
    layout: year
    defaults:
      title: '/year'

categories:
  - usa
  - solo-travel

paginate: 6

paginate_path: "/archive/page:num"
