collections:
- bucket-list
- destinations
- travel-tips

permalink: /:'title'

collections:
  bucket-list:
    output: true
  destinations:
    output: true
  travel-tips:
    output: true


defaults:
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # previously `post` in Jekyll 2.2.
  values:
    layout: "post"
    permalink: /:title

categories:
  - usa
  - solo-travel
  - australia
  - cambodia
  - china
  - india
  - indonesia
  - japan
  - laos
  - malaysia
  - mongolia
  - new-zealand
  - philippines
  - singapore
  - south-korea
  - taiwan
  - thailand
  - vietnam
  - long-term-travel
  - travel-accessories


pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/:num/'
  title: ':title - page :num'
